language: cpp
compiler:
  - clang
  - gcc
before_script:
  - cmake . -DPRD_DEVELOP_FILES:BOOL=ON
script:
  - make -j2
  - sudo make install
  - src/pr-downloader ba:stable
  - src/pr-downloader --rapid-validate
